import fs from 'node:fs';
const scenes = [
 [8,'THE QUESTION','When the pumps stop,\nthe plan matters.','MajiShift helps an operator compare pumping plans before an interruption puts essential water reserves under pressure.','hero'],
 [22,'THE TEAM','Built by Brian & Patrick','Brian Mwangi: backend engineering, Adaption model training and data aggregation. Patrick Leon: frontend development, UI/UX, QA and GIS.','team'],
 [32,'01 / THE PROBLEM','One reservoir. Competing needs.','Essential use, irrigation and pumping availability all draw on the same limited water balance. Operators need to see the trade-offs.','atlas.png'],
 [42,'01 / THE PROBLEM','A decision before an interruption','Our JKUAT pilot exploration asks a practical question: can a proposed schedule maintain a minimum reserve through two unavailable pumping days?','overview.png'],
 [54,'02 / CONDUIT DATA','Real observations. Explicit assumptions.','The historical replay uses official Conduit station 61 observations from 29 August to 4 September 2026. Operating values remain synthetic.','data'],
 [65,'02 / CONDUIT DATA','Temperature becomes a planning input','Daily temperature ranges drive a Hargreaves reference evapotranspiration estimate. Measured rain also enters the water balance; this replay recorded no rain.','weather.png'],
 [76,'02 / CONDUIT DATA','35.6 m³ changes the storage balance','Compared with four millimetres per day, Conduit weather adds 35.6 cubic metres of estimated loss. Total default pumping remains unchanged.','weatherImpact'],
 [87,'03 / SET THE SCENARIO','Start with the operating assumptions','This example starts with 9,000 cubic metres in storage, a 5,000 cubic metre reserve, and essential demand of 1,400 cubic metres daily.','inputs-focus.png'],
 [98,'03 / SET THE SCENARIO','Prepare for two unavailable days','Pumping is unavailable on days two and three. The fixed schedule pumps four hours on available days; the proposed plan prepares a buffer.','decision.png'],
 [110,'04 / COMPARE','Two plans. One water balance.','Both schedules use the same weather and operating assumptions. The teal line follows the proposed schedule; the dashed line follows the fixed schedule.','chart.png'],
 [121,'04 / COMPARE','The reserve is the decision threshold','In this scenario, the fixed schedule falls below the reserve on five days. The proposed schedule stays above the reserve throughout.','metrics.png'],
 [132,'04 / COMPARE','Inspect the trade-off','The proposed plan pumps 7,875 cubic metres versus 5,000 for the fixed schedule. This protects the reserve through more pumping, not water savings.','tradeoff'],
 [144,'05 / REVIEW THE SCHEDULE','A recommendation you can inspect','Day one calls for 4.5 hours of pumping. Days two and three correctly show zero pumping because equipment is unavailable.','schedule.png'],
 [155,'05 / REVIEW THE SCHEDULE','Essential demand comes first','The table exposes each day’s rain, estimated loss, pumping hours and ending storage. Unserved irrigation and unmet essential demand are tracked explicitly.','schedule-detail.png'],
 [168,'06 / CHANGE AN ASSUMPTION','What if starting storage is lower?','Now reduce starting storage from 9,000 to 8,000 cubic metres and compare again. The same weather and outage assumptions remain in place.','edit'],
 [182,'06 / CHANGE AN ASSUMPTION','The recommendation responds','Day-one pumping rises from 4.5 to 8.5 hours. The revised plan builds the same outage buffer from a lower starting level.','edited-decision.png'],
 [196,'07 / KEEP THE EVIDENCE','Export the complete scenario','Export saves the inputs, weather provenance and calculated schedules as JSON. That gives the operator a record to review and share.','export'],
 [207,'08 / HOW IT WORKS','A transparent calculation','React and TypeScript present the planner and GIS view. A shared water-balance module compares schedules; the historical weather replay supplies daily inputs.','architecture'],
 [216,'08 / HOW IT WORKS','Separate the prototype from the research','Adaption model-training experiments are a separate research track. The working schedules shown here come from the transparent planner, not a served AI model.','research'],
 [226,'09 / IMPACT','Make trade-offs visible before acting','The intended benefit is earlier preparation and clearer reserve planning. These scenario results are not measured campus savings or evidence of field performance.','impact'],
 [234,'09 / NEXT STEP','Validate with the operator','Next: approved operating records, calibrated surface-loss estimates and pilot evaluation. Reference evapotranspiration is a proxy, not measured reservoir evaporation.','next'],
 [240,'MAJISHIFT','Keep the reserve.\nPlan the next move.','MajiShift. From environmental observations to an inspectable water-planning decision.','closing'],
].map((s,i,a)=>({end:s[0],start:i?a[i-1][0]:0,chapter:s[1],title:s[2],caption:s[3],visual:s[4]}));
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('\n','<br>');
const image=n=>`<img src="assets/${n}" alt="Actual MajiShift application capture">`;
function body(s){
 if(s.visual.endsWith('.png'))return `<div class="screen ${s.visual==='inputs.png'?'inputs':''}">${image(s.visual)}</div>`;
 switch(s.visual){
 case 'hero': case 'closing':return `<div class="hero"><div class="logo">MajiShift<span>RESERVOIR PLANNING</span></div><div class="wave"></div><p>Conduit weather · Seven-day scenarios · Operator review</p><small>HACK THE WEATHER 2026</small></div>`;
 case 'team':return `<div class="cards"><article><b>01</b><h2>Brian Mwangi</h2><h3>Backend & Model Development</h3><p>Backend engineering<br>Adaption model training<br>Data aggregation</p></article><article><b>02</b><h2>Patrick Leon</h2><h3>Frontend & Geospatial Experience</h3><p>Frontend development · UI/UX<br>Quality assurance<br>GIS</p></article></div>`;
 case 'data':return `<div class="cards three"><article><b>OBSERVED</b><h2>Station 61</h2><p>9,885 observations<br>29 Aug–4 Sep 2026<br>Rain + temperature</p></article><article><b>ESTIMATED</b><h2>32.45 mm</h2><p>Seven-day reference ET<br>FAO-56 Hargreaves<br>Climatic demand proxy</p></article><article><b>ASSUMED</b><h2>Operations</h2><p>Storage and demand<br>Pump availability<br>Reservoir surface area</p></article></div>`;
 case 'weatherImpact':return `<div class="cards three"><article><b>FIXED ASSUMPTION</b><h2>224.0 m³</h2><p>Estimated surface loss<br>4 mm/day × 7 days<br>8,000 m² surface area</p></article><article class="accent"><b>CONDUIT REPLAY</b><h2>259.6 m³</h2><p>Estimated surface loss<br>Daily temperature inputs<br>Same surface area</p></article><article><b>DIFFERENCE</b><h2>+35.6 m³</h2><p>Changes storage outputs<br>Pumping total: 7,875 m³<br>Unchanged at these defaults</p></article></div>`;
 case 'tradeoff':return `<div class="cards"><article><b>FIXED SCHEDULE</b><h2>5 days</h2><h3>below the 5,000 m³ reserve</h3><p>5,000 m³ pumped<br>Lowest storage: 2,190 m³</p></article><article class="accent"><b>PROPOSED SCHEDULE</b><h2>0 days</h2><h3>below the 5,000 m³ reserve</h3><p>7,875 m³ pumped<br>Lowest storage: 5,007 m³</p></article></div>`;
 case 'edit':return `<div class="screen"><video id="edit-video" src="assets/edit.mp4" data-start="${s.start}" data-duration="${s.end-s.start}" data-track-index="2" muted playsinline></video></div>`;
 case 'export':return `<div class="export"><div><h2>majishift-scenario.json</h2><p>Downloaded from the actual app</p><div class="tag">Inputs + source + results</div></div><pre>{\n  "product": "MajiShift",\n  "config": { "initial": 8000, ... },\n  "dailyReferenceEtMm": [...],\n  "conduitReplay": { ... },\n  "assumptions": { ... },\n  "baseline": [...],\n  "plan": [...]\n}</pre></div>`;
 case 'architecture':return `<div class="cards three"><article><b>INPUT</b><h2>Conduit CSV</h2><p>Rain + temperature<br>Daily aggregation<br>Reference ET estimate</p></article><article class="accent"><b>CALCULATE</b><h2>Water balance</h2><p>Storage + inflow − use − loss<br>Reserve-first heuristic<br>Fixed-schedule comparison</p></article><article><b>REVIEW</b><h2>React + GIS</h2><p>Chart and daily table<br>Editable assumptions<br>Scenario export</p></article></div>`;
 case 'research':return `<div class="cards"><article class="accent"><b>RUNNING TODAY</b><h2>Inspectable planner</h2><p>Deterministic water balance<br>Explicit operating constraints<br>Verified calculation tests</p></article><article><b>RESEARCH TRACK</b><h2>Adaption training</h2><p>Synthetic training records<br>Completed experiments<br>Held-out validation still needed</p></article></div>`;
 case 'impact':return `<div class="cards three"><article><b>OBSERVE</b><h2>Use the weather</h2><p>Bring local observations<br>into a planning scenario.</p></article><article><b>COMPARE</b><h2>Expose the risk</h2><p>See reserve breaches<br>and supply constraints.</p></article><article class="accent"><b>REVIEW</b><h2>Prepare earlier</h2><p>Discuss an actionable plan<br>with the responsible operator.</p></article></div>`;
 case 'next':return `<div class="cards three"><article><b>01</b><h2>Verify inputs</h2><p>Approved storage, demand<br>and pumping records.</p></article><article><b>02</b><h2>Calibrate</h2><p>Reservoir surface area<br>and open-water loss estimates.</p></article><article><b>03</b><h2>Pilot & evaluate</h2><p>Operator review, measured<br>outcomes and iteration.</p></article></div>`;
 }
}
const html=`<!doctype html><html><head><meta charset="utf-8"><title>MajiShift demo</title><style>
*{box-sizing:border-box}html,body{margin:0;background:#0e3443;font-family:Arial,Helvetica,sans-serif}#root{position:relative;width:1920px;height:1080px;overflow:hidden;color:#f4f7fa;background:#0e3443}.scene{position:absolute;inset:0;padding:60px 80px 165px;opacity:0;visibility:hidden}.chapter{font-size:22px;letter-spacing:4px;font-weight:700;color:#8edcd5;margin-bottom:20px}.title{font-size:58px;line-height:1.08;letter-spacing:-1.8px;margin:0 0 26px;font-weight:600}.content{height:645px;display:flex;align-items:center;justify-content:center}.screen{width:100%;height:100%;display:flex;align-items:center;justify-content:center;overflow:hidden;border-radius:18px}.screen img{width:100%;height:100%;max-width:100%;max-height:100%;object-fit:contain;border-radius:14px;box-shadow:0 18px 60px #061c2570}.screen.inputs img{height:auto;max-height:none;width:590px;align-self:flex-start;transform:translateY(-15px)}video{width:100%;height:100%;object-fit:contain}.caption{position:absolute;left:80px;right:80px;bottom:50px;min-height:90px;border-top:1px solid #527783;padding-top:22px;font-size:34px;line-height:1.35;color:#fff}.cards{display:flex;gap:28px;width:100%}.cards article{flex:1;padding:45px 40px;min-height:440px;border:1px solid #527783;border-radius:18px;background:#123d4d}.cards article.accent{background:#e6f3ef;color:#173342;border-color:#e6f3ef}b{font-size:23px;letter-spacing:2px;color:#8edcd5}.accent b{color:#087f84}h2{font-size:52px;letter-spacing:-1.4px;margin:32px 0 20px}h3{font-size:27px;font-weight:500;line-height:1.3;margin:10px 0}p{font-size:30px;line-height:1.7;color:#d4e5e9}.accent p{color:#325e62}.three h2{font-size:43px}.three p{font-size:27px}.hero{text-align:center;width:100%}.logo{font-size:120px;font-weight:750;letter-spacing:-6px}.logo span{display:block;font-size:24px;letter-spacing:7px;color:#8edcd5;margin-top:15px}.hero p{font-size:30px}.hero small{font-size:20px;letter-spacing:5px;color:#bdd3dc}.wave{height:7px;background:linear-gradient(90deg,transparent,#8edcd5,transparent);width:800px;margin:40px auto}.export{display:flex;align-items:center;gap:80px}.export h2{font-size:43px}.export pre{background:#f4f7fa;color:#173342;padding:35px;border-radius:16px;font:27px/1.55 Consolas,monospace}.tag{font-size:25px;border:1px solid #8edcd5;padding:16px;border-radius:8px}.brand{position:absolute;right:80px;top:54px;color:#bdd3dc;font-size:21px;letter-spacing:2px}.progress{position:absolute;bottom:0;left:0;width:0;height:6px;background:#8edcd5}.foot{position:absolute;bottom:15px;right:80px;font-size:16px;color:#bdd3dc}
</style></head><body><div id="root" data-composition-id="root" data-width="1920" data-height="1080" data-duration="240"><div class="brand">MAJISHIFT / DEMO</div>${scenes.map((s,i)=>`<section id="scene-${i}" class="scene"><div class="chapter">${esc(s.chapter)}</div><h1 class="title">${esc(s.title)}</h1><div class="content">${body(s)}</div><div class="caption">${esc(s.caption)}</div></section>`).join('')}<div class="foot">Historical weather · Synthetic operations · Working prototype</div><div class="progress"></div></div><script src="assets/gsap.min.js"></script><script>
const tl=gsap.timeline({paused:true});
${scenes.map((s,i)=>`tl.set('#scene-${i}',{visibility:'visible'},${s.start});tl.to('#scene-${i}',{opacity:1,duration:0.35},${s.start});tl.fromTo('#scene-${i} .content',{y:12},{y:0,duration:0.6},${s.start});tl.set('#scene-${i}',{opacity:0,visibility:'hidden'},${s.end});`).join('\n')}
tl.to('.progress',{width:1920,duration:240,ease:'none'},0);window.__timelines={root:tl};
</script></body></html>`;
fs.writeFileSync('brag-output/composition/index.html',html);
fs.copyFileSync('brag-output/tools/node_modules/gsap/dist/gsap.min.js','brag-output/composition/assets/gsap.min.js');
fs.writeFileSync('brag-output/scenes.json',JSON.stringify(scenes,null,2));
const stamp=s=>new Date(s*1000).toISOString().slice(11,23).replace('.',',');
fs.writeFileSync('brag-output/MajiShift-captions.srt',scenes.map((s,i)=>`${i+1}\n${stamp(s.start)} --> ${stamp(s.end)}\n${s.caption}\n`).join('\n'));
fs.writeFileSync('brag-output/narration-script.md','# MajiShift — optional narration\n\n240 seconds. Read naturally within each time window; pauses allow the viewer to inspect the app. No narration is embedded in the silent MP4.\n\n'+scenes.map(s=>`## ${stamp(s.start).slice(0,8)}–${stamp(s.end).slice(0,8)} | ${s.chapter}\n\n${s.caption}`).join('\n\n'));
fs.writeFileSync('brag-output/composition/DESIGN.md','# MajiShift video design\n\n1920×1080. Navy #0e3443, teal #087f84, pale teal #8edcd5, paper #f4f7fa. Arial. 58px headings; 34px captions. Actual UI capture within a clean editorial frame. Intentional silence. Editable scene source: ../build-video.mjs.');
fs.writeFileSync('brag-output/share-copy.txt','MajiShift turns Conduit weather observations into an inspectable seven-day water-planning scenario. Compare pumping schedules, review reserve risks, and export the assumptions behind the decision.');
console.log(`Built ${scenes.length} scenes; ${scenes.at(-1).end} seconds.`);
