import { chromium } from './tools/node_modules/playwright/index.mjs';
import fs from 'node:fs';
import path from 'node:path';
const out=path.resolve('brag-output/composition/assets');
const browser=await chromium.launch({executablePath:'C:/Users/HP/.cache/hyperframes/chrome/chrome-headless-shell/win64-152.0.7977.30/chrome-headless-shell-win64/chrome-headless-shell.exe',headless:true,args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:1500,height:900},deviceScaleFactor:1,recordVideo:{dir:out,size:{width:1500,height:900}}});
const page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:3000/',{waitUntil:'networkidle',timeout:120000});
await page.screenshot({path:path.join(out,'overview.png')});
await page.locator('.metrics').screenshot({path:path.join(out,'metrics.png')});
await page.locator('.main-panel > .change-card').first().screenshot({path:path.join(out,'weather.png')});
await page.locator('.campus-atlas').screenshot({path:path.join(out,'atlas.png')});
await page.locator('.chart-card').screenshot({path:path.join(out,'chart.png')});
await page.locator('.schedule').screenshot({path:path.join(out,'schedule.png')});
await page.locator('.inputs').screenshot({path:path.join(out,'inputs.png')});
await page.locator('.decision').screenshot({path:path.join(out,'decision.png')});
await page.getByLabel('Starting storage',{exact:false}).fill('8000');
await page.getByRole('button',{name:'Compare schedules'}).click();
await page.locator('.decision').screenshot({path:path.join(out,'edited-decision.png')});
await page.locator('.chart-card').screenshot({path:path.join(out,'edited-chart.png')});
await page.locator('.schedule').screenshot({path:path.join(out,'edited-schedule.png')});
const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Export scenario'}).click()]);
await download.saveAs('brag-output/evidence/majishift-scenario.json');
fs.writeFileSync('brag-output/evidence/browser-qa.json',JSON.stringify({errors,metrics:await page.locator('.metrics').innerText(),decision:await page.locator('.decision').innerText(),download:download.suggestedFilename()},null,2));
const video=page.video();await context.close();await video.saveAs(path.join(out,'workflow.webm'));await browser.close();
console.log('Captured actual application visuals and exported scenario.');
