import { chromium } from './tools/node_modules/playwright/index.mjs';
import { spawnSync } from 'node:child_process';
import ffmpeg from './tools/node_modules/ffmpeg-static/index.js';
import path from 'node:path';
const browser=await chromium.launch({executablePath:'C:/Users/HP/.cache/hyperframes/chrome/chrome-headless-shell/win64-152.0.7977.30/chrome-headless-shell-win64/chrome-headless-shell.exe',headless:true,args:['--no-sandbox']});
const ctx=await browser.newContext({viewport:{width:1500,height:900},recordVideo:{dir:'brag-output/evidence/edit-recording',size:{width:1500,height:900}}});
const page=await ctx.newPage();const recorded=Date.now();
await page.goto('http://localhost:3000/',{waitUntil:'networkidle'});
const field=page.getByLabel('Starting storage',{exact:false});
await field.scrollIntoViewIfNeeded();
const start=(Date.now()-recorded)/1000;
await page.waitForTimeout(2500);
await field.fill('8000');
await page.waitForTimeout(2500);
await page.getByRole('button',{name:'Compare schedules'}).click();
await page.waitForTimeout(1800);
await page.locator('.decision').scrollIntoViewIfNeeded();
await page.waitForTimeout(7000);
const video=page.video();await ctx.close();const source=await video.path();await browser.close();
const r=spawnSync(ffmpeg,['-y','-ss',String(start),'-i',source,'-t','13','-an','-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p',path.resolve('brag-output/composition/assets/edit.mp4')],{encoding:'utf8'});
console.log(r.status===0?'Recorded and encoded storage edit.':r.stderr);process.exitCode=r.status;
